services:
  mysql:
    container_name: java_mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: mircodev
      MYSQL_PASSWORD: mircodevpass
    ports:
      - 3306:3306
    volumes:
      - mysql_java_data:/var/lib/mysql
    networks:
      - javaLibraryNetwork

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - javaLibraryNetwork

volumes:
  mysql_java_data:
    driver: local
networks:
  javaLibraryNetwork:
    driver: bridge